#!/bin/bash
#PBS -S /bin/bash
# Use 1 core on 1 node
#PBS -l nodes=1:ppn=8
# Maximum time to run of 20 minues 
#PBS -l walltime=00:20:00 
                          

module load gcc/4.3.3 # NEED TO LOAD CORRECT
                      # VERSION OF GCC
cd $PBS_O_WORKDIR     # Change to directory from 
                      # which job was submitted
                      
SIZE="100"
OUTPUT_FILE="mpi_output"

mpirun -np 8 ./laplace <<END >> $OUTPUT_FILE
$SIZE
$SIZE
$SIZE
0.01
100
2
2
2
END